bookstore_app/config/routes.rb
Rails.application.routes.draw do
  get 'novels/index'
  get 'novels/show'
  get 'novels/new'
  get 'novels/create'
  get 'novels/update'
  get 'novels/edit'
  get 'novels/destroy'
  get 'publishers/index'
  get 'publishers/show'
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'genres/index'
  get 'genres/show'
  get 'genres/new'
  get 'genres/create'
  get 'genres/update'
  get 'genres/edit'
  get 'genres/destroy'
  get 'authors/index'
  get 'authors/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/destroy'
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :books
  resources :authors do
    collection do
      get :search
    end
  end
  resources :genres
  resources :publishers
  resources :novels do
    collection do
      get :search
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookstore_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookstore_app/app/models/author.rb
class Author < ApplicationRecord
	has_many :novels

	validates:fname, presence: true
	validates:lname, presence: true
	validates:bio, presence: true
end

bookstore_app/app/models/book.rb
class Book < ApplicationRecord
end

bookstore_app/app/models/genre.rb
class Genre < ApplicationRecord
	has_many :novels

	validates:name, presence: true, length: {minimum: 3}
end

bookstore_app/app/models/novel.rb
class Novel < ApplicationRecord
	belongs_to :author
	belongs_to :genre
	belongs_to :publisher
end

bookstore_app/app/models/publisher.rb
class Publisher < ApplicationRecord
	has_many :novels

	validates:name, presence: true
	validates:country, presence: true
end

bookstore_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookstore_app/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @author=Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @novel = Novel.new
    @genre = Genre.new
    @publisher = Publisher.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to authors_path
    else
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def search
    @author = if params[:term]
      Author.where('lname LIKE ?', "%#{params[:term]}")
    else
      Author.all
    end
  end

  private
    def author_params
      params.require(:author) .permit(:fname, :lname, :bio)
    end
end

bookstore_app/app/controllers/books_controller.rb
class BooksController < ApplicationController

	def new
	end

	def create
		# render plain: params[:book] .inspect
		@book=Book.new(book_params)
		@book.save
		redirect_to @book
	end

	def show
		@book=Book.find(params[:id])
	end

	def index
		@books=Book.all
	end

	private 
		def book_params
			params.require(:book) .permit(:title, :price, :book_id, :publisher, :description, :number)
		end
end

bookstore_app/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genre=Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @novel = Novel.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path
    else
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end
  private
    def genre_params
      params.require(:genre) .permit(:name)
    end
end

bookstore_app/app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  def index
    @novel=Novel.all
  end

  def show
    @novel = Novel.find(params[:id])
  end

  def new
    @novel = Novel.new
    @publisher = Publisher.new
    @genre = Genre.new
    @author = Author.new
  end

  def create
    @novel = Novel.new(novel_params)
    if @novel.save
      redirect_to novels_path
    else
      render 'new'
    end
  end

  def update
    @novel = Novel.find(params[:id])
    if @novel.update(novel_params)
      redirect_to @novel
    else
      render 'edit'
    end
  end

  def edit
    @novel = Novel.find(params[:id])
  end

  def destroy
    @novel = Novel.find(params[:id])

    @novel.destroy

    redirect_to novels_path
  end

  def search
    @novel = if params[:term]
      Novel.where('title LIKE ? OR format LIKE ?', "%#{params[:term]}", "%#{params[:term]}")
    else
      Novel.all
    end
  end

  private
    def novel_params
      params.require(:novel) .permit(:title, :genre_id, :author_id, :publisher_id, :price, :isbn, :publication, :format, :description, :pages)
    end
end

bookstore_app/app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @publisher=Publisher.all
  end

  def show
    @publisher = Publisher.find(params[:id])
  end

  def new
    @novel = Novel.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      redirect_to publishers_path
    else
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end
  private
    def publisher_params
      params.require(:publisher) .permit(:name, :country)
    end
end

bookstore_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

bookstore_app/app/helpers/application_helper.rb
module ApplicationHelper
end

bookstore_app/app/helpers/authors_helper.rb
module AuthorsHelper
end

bookstore_app/app/helpers/books_helper.rb
module BooksHelper
end

bookstore_app/app/helpers/genres_helper.rb
module GenresHelper
end

bookstore_app/app/helpers/novels_helper.rb
module NovelsHelper
end

bookstore_app/app/helpers/publishers_helper.rb
module PublishersHelper
end

bookstore_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

bookstore_app/app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

bookstore_app/app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

bookstore_app/app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

bookstore_app/app/views/authors/index.html.erb
<div class="container">
	<h2> Authors Available </h2>
	<table border="1" class="table">
		<tr>
			<th>Author First Name</th>
			<th>Author Last Name</th>
			<th>Author Bio</th>
			<th>Author Page</th>
		</tr>
		<% @author.each do |author| %>
			<tr>
				<td> <%= author.fname %> </td>
				<td> <%= author.lname %> </td>
				<td> <%= author.bio %> </td>
				<td> <%= link_to 'Author Page', author_path(author) %> </td>
			</tr>
		<% end %>
	</table> 
</div>

bookstore_app/app/views/authors/new.html.erb
<div class="container">
	<h2>Add New Author</h2>
	<%= form_for :author, url: authors_path do |f| %>
		<div class="form-group">
			<%= f.label :fname %> <br />
			<%= f.text_field :fname, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :lname %> <br />
			<%= f.text_field :lname, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :bio %> <br />
			<%= f.text_area :bio, class:'form-control' %> <br />
		</div>
		<%= f.submit "Submit", class:'btn btn-primary' %>
			<%=link_to "Cancel", authors_path, class:'btn btn-default' %>
		<% end %>
</div>

bookstore_app/app/views/authors/search.html.erb
<div class="container">
		<%= form_tag search_authors_path, method: :get do %>
	<%=text_field_tag :term, nil, placeholder: 'Search', class:'form-control' %>
	<%= submit_tag "Search", class:'btn btn-default' %>
	<% end %>
	<h2> Authors Available </h2>
	<table border="1" class="table">
		<tr>
			<th>Author First Name</th>
			<th>Author Last Name</th>
			<th>Author Bio</th>
			<th>Author Page</th>
		</tr>
		<% @author.each do |author| %>
			<tr>
				<td> <%= author.fname %> </td>
				<td> <%= author.lname %> </td>
				<td> <%= author.bio %> </td>
				<td> <%= link_to 'Author Page', author_path(author) %> </td>
			</tr>
		<% end %>
	</table> 
</div>

bookstore_app/app/views/authors/show.html.erb
<div class="container">
	<h3>Author Details</h3>
	<p>Author First Name: <%= @author.fname %> </p>
	<p>Author Last Name: <%= @author.lname %> </p>
	<p>Author Bio: <%= @author.bio %> </p>
</div>

bookstore_app/app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

bookstore_app/app/views/books/index.html.erb
<div class="container">
	<h2> Books Available </h2>
	<table border="1" class="table">
		<tr>
			<th>Book Title</th>
			<th>Book Code</th>
			<th>Book Price</th>
			<th>Book Publisher</th>
			<th>Book Description</th>
			<th>Book Number of Copies</th>
			<th>Book Page</th>
		</tr>
		<% @books.each do |book| %>
			<tr>
				<td> <%= book.title %> </td>
				<td> <%= book.book_id %> </td>
				<td> <%= book.price %> </td>
				<td> <%= book.publisher %> </td>
				<td> <%= book.description %> </td>
				<td> <%= book.number %> </td>
				<td> <%= link_to 'Book Page', book_path(book) %> </td>
			</tr>
		<% end %>
	</table> 
</div>

bookstore_app/app/views/books/new.html.erb
<div class="container">
	<h1> Add New Book </h1>
	<%= form_for :book, url: books_path do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="form-group">
		<%= f.label :price %>
		<%= f.number_field :price %>
	</div>
	<div class="form-group">
		<%= f.label :book_id %>
		<%= f.text_field :book_id %>
	</div>
	<div class="form-group">
		<%= f.label :publisher %>
		<%= f.text_field :publisher %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	<div class="form-group">
		<%= f.label :number %>
		<%= f.number_field :number %>
	</div>
	<div class="form-group">
		<%= f.submit %>
	</div>
	<% end %>
</div>

bookstore_app/app/views/books/show.html.erb
<div class="container">
	<h3>Book Details</h3>
	<p>Book Title: <%= @book.title %> </p>
	<p>Book Code: <%= @book.book_id %> </p>
	<p>Book Price: <%= @book.price %> </p>
	<p>Book Description: <%= @book.description %> </p>
	<p>Book Number of Copies: <%= @book.number %> </p>
</div>

bookstore_app/app/views/genres/create.html.erb
<h1>Genres#create</h1>
<p>Find me in app/views/genres/create.html.erb</p>

bookstore_app/app/views/genres/destroy.html.erb
<h1>Genres#destroy</h1>
<p>Find me in app/views/genres/destroy.html.erb</p>

bookstore_app/app/views/genres/edit.html.erb
<h1>Genres#edit</h1>
<p>Find me in app/views/genres/edit.html.erb</p>

bookstore_app/app/views/genres/index.html.erb
<div class="container">
	<h2> Genres Available </h2>
	<table border="1" class="table">
		<tr>
			<th>Genre Name</th>
			<th>Genre Page</th>
		</tr>
		<% @genre.each do |genre| %>
			<tr>
				<td> <%= genre.name %> </td>
				<td> <%= link_to 'Genre Page', genre_path(genre) %> </td>
			</tr>
		<% end %>
	</table> 
</div>

bookstore_app/app/views/genres/new.html.erb
<div class="container">
	<h2>Add New Author</h2>
	<%= form_for :genre, url: genres_path do |f| %>
		<div class="form-group">
			<%= f.label :name %> <br />
			<%= f.text_field :name, class:'form-control' %> <br />
		</div>
		<%= f.submit "Submit", class:'btn btn-primary' %>
			<%=link_to "Cancel", genres_path, class:'btn btn-default' %>
		<% end %>
</div>

bookstore_app/app/views/genres/show.html.erb
<h1>Genres#show</h1>
<p>Find me in app/views/genres/show.html.erb</p>

bookstore_app/app/views/genres/update.html.erb
<h1>Genres#update</h1>
<p>Find me in app/views/genres/update.html.erb</p>

bookstore_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookstoreApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">

   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

      <h5 class="my-0 mr-md-auto font-weight-normal"> Sheffield Bookstore </h5>

      <nav class="my-2 my-md-0 mr-md-3">


        <!-- <a class="p-2 text-dark" href="#"> Link 1 </a> -->
        <%= link_to "Home", '#' %>
<!-- <a class="p-2 text-dark" href="#"> Link 2 </a> -->
        <%= link_to "About Us", '#' %>
        <!-- <a class="p-2 text-dark" href="#"> Link 3 </a> -->
        <%= link_to "Contact Us", '#' %>
        <%= link_to "Add New Book", new_book_path %>
        <%= link_to "Add New Novel", new_novel_path %>
        <%= link_to "View Novels", novels_path %>
        <%= link_to "Add New Author", new_author_path %>
        <%= link_to "Add New Genre", new_genre_path %>
        <%= link_to "Add New Publisher", new_publisher_path %>
       
      </nav>
    </div>
</div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

bookstore_app/app/views/novels/create.html.erb
<h1>Novels#create</h1>
<p>Find me in app/views/novels/create.html.erb</p>

bookstore_app/app/views/novels/destroy.html.erb
<h1>Novels#destroy</h1>
<p>Find me in app/views/novels/destroy.html.erb</p>

bookstore_app/app/views/novels/edit.html.erb
<div class="container">
	<h2>Edit Novel Details</h2>
	<%= form_for @novel do |f| %>
		<div class="form-group">
			<%= f.label :title %> <br />
			<%= f.text_field :title, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :isbn %> <br />
			<%= f.text_field :isbn, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :format %> <br />
			<%= f.text_field :format, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :genre %> <br />
			<%= f.select :genre_id, Genre.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Genre'}, class:'form-control'%> <br /> 
			<br />
		</div> 
		<div class="form-group">
			<%= f.label :publisher %> <br />
			<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Publisher'}, class:'form-control'%> <br /> <br />
		</div> 
		<div class="form-group">
			<%= f.label :author %> <br />
			<%= f.select :author_id, Author.all.collect {|x| [x.fname + ' ' + x.lname, x.id]}, {:include_blank => 'Select Publisher'}, class:'form-control'%> <br /> <br />
		</div> 
		<div class="form-group">
			<%= f.label :price %> <br />
			<%= f.text_field :price, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :pages %> <br />
			<%= f.text_field :pages, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :publication %> <br />
			<%= f.text_field :publication, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :description %> <br />
			<%= f.text_area :description, class:'form-control' %> <br />
		</div>
		<%= f.submit "Submit", class:'btn btn-primary' %>
			<%=link_to "Cancel", novels_path, class:'btn btn-default' %>
		<% end %>
</div>

bookstore_app/app/views/novels/index.html.erb
<div class="container">
	<h2> Novels Available </h2>
	<table border="1" class="table">
		<tr>
			<th>Novels Title</th>
			<th>Author ID</th>
			<th>Publisher ID</th>
			<th>Genre ID</th>
			<th>Price</th>
			<th>ISBN</th>
			<th>Publication</th>
			<th>Pages</th>
			<th>Format</th>
			<th>Description</th>
			<th>Details</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
		<% @novel.each do |novel| %>
			<tr>
				<td> <%= novel.title %> </td>
				<td> <%= novel.author_id %> </td>
				<td> <%= novel.publisher_id %> </td>
				<td> <%= novel.genre_id %> </td>
				<td> <%= novel.price %> </td>
				<td> <%= novel.isbn %> </td>
				<td> <%= novel.publication %> </td>
				<td> <%= novel.pages %> </td>
				<td> <%= novel.format %> </td>
				<td> <%= novel.description %> </td>
				<td> <%= link_to 'Novel Page', novel_path(novel) %> </td>
				<td> <%= link_to 'Edit', edit_novel_path(novel) %> </td>
				<td> <%= link_to 'Delete', novel_path(novel), method: :Delete, data: {confirm: "Are you sure you want to delete details"} %> </td>
			</tr>
		<% end %>
	</table> 
</div>

bookstore_app/app/views/novels/new.html.erb
<div class="container">
	<h2>Add New Novel</h2>
	<%= form_for :novel, url: novels_path do |f| %>
		<div class="form-group">
			<%= f.label :title %> <br />
			<%= f.text_field :title, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :isbn %> <br />
			<%= f.text_field :isbn, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :format %> <br />
			<%= f.text_field :format, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :genre %> <br />
			<%= f.select :genre_id, Genre.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Genre'}, class:'form-control'%> <br /> 
			<br />
		</div> 
		<div class="form-group">
			<%= f.label :publisher %> <br />
			<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Publisher'}, class:'form-control'%> <br /> <br />
		</div> 
		<div class="form-group">
			<%= f.label :author %> <br />
			<%= f.select :author_id, Author.all.collect {|x| [x.fname + ' ' + x.lname, x.id]}, {:include_blank => 'Select Publisher'}, class:'form-control'%> <br /> <br />
		</div> 
		<div class="form-group">
			<%= f.label :price %> <br />
			<%= f.text_field :price, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :pages %> <br />
			<%= f.text_field :pages, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :publication %> <br />
			<%= f.text_field :publication, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :description %> <br />
			<%= f.text_area :description, class:'form-control' %> <br />
		</div>
		<%= f.submit "Submit", class:'btn btn-primary' %>
			<%=link_to "Cancel", novels_path, class:'btn btn-default' %>
		<% end %>
</div>

bookstore_app/app/views/novels/search.html.erb
<div class="container">
	<%= form_tag search_novels_path, method: :get do %>
	<%=text_field_tag :term, nil, placeholder: 'Search', class:'form-control' %>
	<%= submit_tag "Search", class:'btn btn-default' %>
	<% end %>
	<h2> Novels Available </h2>
	<table border="1" class="table">
		<tr>
			<th>Novels Title</th>
			<th>Author ID</th>
			<th>Publisher ID</th>
			<th>Genre ID</th>
			<th>Price</th>
			<th>ISBN</th>
			<th>Publication</th>
			<th>Pages</th>
			<th>Format</th>
			<th>Description</th>
			<th>Details</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
		<% @novel.each do |novel| %>
			<tr>
				<td> <%= novel.title %> </td>
				<td> <%= novel.author_id %> </td>
				<td> <%= novel.publisher_id %> </td>
				<td> <%= novel.genre_id %> </td>
				<td> <%= novel.price %> </td>
				<td> <%= novel.isbn %> </td>
				<td> <%= novel.publication %> </td>
				<td> <%= novel.pages %> </td>
				<td> <%= novel.format %> </td>
				<td> <%= novel.description %> </td>
				<td> <%= link_to 'Novel Page', novel_path(novel) %> </td>
				<td> <%= link_to 'Edit', edit_novel_path(novel) %> </td>
				<td> <%= link_to 'Delete', novel_path(novel), method: :Delete, data: {confirm: "Are you sure you want to delete details"} %> </td>
			</tr>
		<% end %>
	</table> 
</div>

bookstore_app/app/views/novels/show.html.erb
<div class="container">
	<h3>Novel Details</h3>
	<p>Novel Title <%= @novel.title %> </p>
	<p>Novel Author ID <%= @novel.author_id %> </p>
	<p>Novel Publisher ID <%= @novel.publisher_id %> </p>
	<p>Novel Genre ID <%= @novel.genre_id %> </p>
	<p>Novel Price <%= @novel.price %> </p>
	<p>Novel Publication <%= @novel.publication %> </p>
	<p>Novel Pages <%= @novel.pages %> </p>
	<p>Novel Format <%= @novel.format %> </p>
	<p>Novel Description <%= @novel.description %> </p>
</div>

bookstore_app/app/views/novels/update.html.erb
<h1>Novels#update</h1>
<p>Find me in app/views/novels/update.html.erb</p>

bookstore_app/app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

bookstore_app/app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

bookstore_app/app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

bookstore_app/app/views/publishers/index.html.erb
<div class="container">
	<h2> Publishers Available </h2>
	<table border="1" class="table">
		<tr>
			<th>Publisher Name</th>
			<th>Publisher Country</th>
			<th>Publisher Page</th>
		</tr>
		<% @publisher.each do |publisher| %>
			<tr>
				<td> <%= publisher.name %> </td>
				<td> <%= publisher.country %> </td>
				<td> <%= link_to 'Publisher Page', publishers_path(publisher) %> </td>
			</tr>
		<% end %>
	</table> 
</div>

bookstore_app/app/views/publishers/new.html.erb
<div class="container">
	<h2>Add New Publisher</h2>
	<%= form_for :publisher, url: publishers_path do |f| %>
		<div class="form-group">
			<%= f.label :name %> <br />
			<%= f.text_field :name, class:'form-control' %> <br />
		</div>
		<div class="form-group">
			<%= f.label :country %> <br />
			<%= f.text_field :country, class:'form-control' %> <br />
		</div>
		<%= f.submit "Submit", class:'btn btn-primary' %>
			<%=link_to "Cancel", publishers_path, class:'btn btn-default' %>
		<% end %>
</div>

bookstore_app/app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

bookstore_app/app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>

bookstore_app/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

bookstore_app/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

bookstore_app/app/views/static_pages/home.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Album Example</h1>
</div>
<div class="container">
	<div class="row">
		<div class="col"> 
			<p> THIS IS SOME TEXT IHRFIH :LHDIHBF :IHODH HIFHPI HFDIHDIHF IHIFHIFH HFIHFH IHF :FHF HF IH:K HFKHB FGSUHS HBDLJHBD JHFDLHF HFLJH FLKJHD LJNLJNS LJNB</p>
		</div>
		<div class="col">
			<p> THIS IS SOME TEXT IHRFIH :LHDIHBF :IHODH HIFHPI HFDIHDIHF IHIFHIFH HFIHFH IHF :FHF HF IH:K HFKHB FGSUHS HBDLJHBD JHFDLHF HFLJH FLKJHD LJNLJNS LJNB</p>
		</div>
	</div>
</div>